flags:
packages:
- '.'
extra-deps:
- OptDir-0.0.3
- data-interval-1.2.0
- extended-reals-0.2.2.0
- finite-field-0.8.0
- incremental-sat-solver-0.1.8
- sign-0.4.3
- intern-0.9.1.4
- parse-dimacs-1.3
- pseudo-boolean-0.1.6.0
- queue-0.1.2
- toysolver-0.4.0
resolver: lts-9.5
